import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import NewTask from '../components/tasks/newTask'
import { useState } from 'react'
import TableTask from '../components/tasks/tableTask'
import TableSongs from '../components/songs/tableSong'
import React from "react";
import { LinkButton, ShowListButton } from "../components/ui/button";


export default function Home() {
  const [tasksItems, setTasksItems] = useState([]);
  const [songsItems, setSongsItems] = useState([]);
  const [showTaskTable, setShowTaskTable] = useState(false);
  const [showSongTable, setShowSongTable] = useState(false);
  const TasksPage = '/tasks';
  const SongsPage = '/songs';

  function showTasks() {
    setShowTaskTable(!showTaskTable);
    fetch('/api/tasks')
      .then((response) => response.json())
      .then((data) => {
        setTasksItems(data.tasks)
      });
    //console.log(tasksItems);
  }

  function showSongs() {
    setShowSongTable(!showSongTable);
    fetch('/api/songs')
      .then((response) => response.json())
      .then((data) => {
        setSongsItems(data.songs)
      });
    //console.log(songsItems);
  }


  const [showList, setShowList] = useState(false);
  const toggleShowList = () => {
    setShowList(!showList);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Calcula tu Productividad
        </h1>

        <div className={styles.grid}>
          <p>
            Ingresa ahora y descubre tus momentos más productivos!
          </p>
        </div>

        <br />
        {/* Ingresa nueva Tarea */}
        {/* <div className={styles.card}>
          <NewTask />
        </div> */}

        {/* ----- Mostrar Tareas ----- */}
        {/* <button onClick={showTasks}>Ver Tareas</button>
        {showTaskTable && <TableTask tasks={tasksItems} />} */}
        
        {/* mostrar u ocultar tabla de tareas */}
        <br />
        <ShowListButton
          text="Ver Tareas Ingresadas"
          toggleShowList={toggleShowList}
          fetchData={showTasks}
        />
        {showList && <TableTask tasks={tasksItems} />}
        <br />
        <LinkButton text="Más Detalles ->" link={TasksPage} />

        {/* ----- Mostrar Canciones ----- */}
        <br />
        <br />
        <br />
        {/* <button onClick={showSongs}>Ver Canciones</button>
        {showSongTable && <TableSongs songs={songsItems} />} */}
        <ShowListButton
          text="Ver Canciones Ingresadas"
          toggleShowList={toggleShowList}
          fetchData={showTasks}
        />
        {showList && <TableTask tasks={tasksItems} />}

      </main>

      <footer className={styles.footer}>
        <p>
          Core - Ingeniería Web
        </p>
      </footer>
    </div>
  )
}
