import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import NewTask from '../components/tasks/newTask'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          HOME NO AUTENTIFICADO
        </h1>

        <div className={styles.grid}>
          <p>
            Layout con: Home, Perfil y Registrarse 
            <br/>
          </p>
          
          <p>
            BPM más usado con la tarea más realizada
            <br/>
             Y Mejor nivel de productividad
          </p>
          <NewTask/>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Core - Ingeniería Web
        </a>
      </footer>
    </div>
  )
}
